# Generated by Django 5.0.7 on 2024-08-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('key', models.CharField(blank=True, max_length=32, null=True)),
                ('snippet_id', models.CharField(max_length=8, unique=True)),
            ],
        ),
    ]
